services:
    postgres:
        image: postgres:17.5
        container_name: oficina_soat_postgres
        restart: always
        ports:
        - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
        - oficina_soat_pg_data:/var/lib/postgresql/data
        networks:
            - oficina_soat_network

    nginx:
        image: nginx:1.28
        container_name: oficina_soat_nginx
        restart: always
        ports:
        - "8080:80"
        volumes:
        - ./app:/var/www/html
        - ./docker/nginx/http.d/default.conf:/etc/nginx/conf.d/default.conf
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - oficina_soat_network
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: oficina_soat_php
        restart: always
        ports:
        - "9000:9000"
        volumes:
        - ./app:/var/www/html
        networks:
            - oficina_soat_network
        depends_on:
            - postgres

volumes:
    oficina_soat_pg_data:

networks:
  oficina_soat_network:
    name: oficina_soat_network
    driver: bridge
