version: '3'

services:
  sonar:
    image: sonarqube:community
    ports:
      - "9999:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    networks:
      - sonarnet
    depends_on:
      - db

  db:
    image: postgres:17.5
    ports:
        - "5499:5432"
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    networks:
      - sonarnet

networks:
  sonarnet:
    driver: bridge